name: Lint DAGs

on: [push]

jobs:
  Deploy:
    name: Lint DAGs
    runs-on: ubuntu-22.04
    container:
      image: apache/airflow:1.10.14-python3.7
      options: --user 0
    steps:
    - uses: actions/checkout@v2
    - name: Install pylint
      run: pip install pylint===2.6.0
    - name: Run pylint
      run: ./lint.sh